name: Build App
on: 
   push:            #This runs it when you save the code
   workflow_dispatch:     #THIS is the line that add the Manual Button
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: pip install flet yt-dlp
      - name: Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Build APK
        run: |
          # This command helps Flet find everything it needs
          flet build apk --verbose 
      - name: Upload APK
      - uses: actions/upload-artifact@v4
        with:
          name: universal-downloader-apk
          path: build/apk/*.apk
